#!/bin/bash

set -euxo pipefail

if [ ! -f "${SNAP_USER_COMMON}/node.conf" ]; then
	${SNAP}/bin/config.py othernodes=
fi

if [ ! -f "${SNAP_USER_COMMON}/node.pub" ]; then
	${SNAP}/bin/constellation-node --workdir=${SNAP_USER_COMMON} --generatekeys=node
fi

exec ${SNAP}/bin/constellation-node --workdir=${SNAP_USER_COMMON} ${SNAP_USER_COMMON}/node.conf "$@"
